from env import *
from itertools import chain

def plot_cobweb(base, P, S, D, Sfun, Dfun, fname, n_colors):
    plt.figure(figsize=FIG_SIZE_2D, dpi=FIG_DPI_2D)
    plt.plot(base, P, label='P')
    plt.ylabel('Prezzo')
    plt.legend(loc='lower right',prop={'size':12})
    plt.grid(**GRID_OPTIONS)
    plt.twinx()
    plt.plot(base, S, label='S', color='g')
    plt.plot(base, D, label='D', color='r')
    plt.legend(loc='upper right',prop={'size':12})
    plt.ylabel('Domanda/Offerta')
    plt.xlabel('Iterazione')
    plt.grid(**GRID_OPTIONS_TWIN)
    plt.savefig('./figs/%s-time.eps'%fname, dpi=SAVE_FIG_DPI)
    plt.figure(figsize=FIG_SIZE_2D, dpi=FIG_DPI_2D)
    pbase = list(chain(*zip(P,P[:-1])))
    pvals = list(chain(*zip(D,S[1:])))
    pbase_diff = np.diff(np.array(pbase))
    pvals_diff = np.diff(np.array(pvals))
    Pmin, Pmax = min(P), max(P)
    border = Pmax*0.1
    color_map_gen = color_map_generator(n_colors, repeat=2)
    colors = [color_map_gen.next() for _ in range(len(pbase_diff))]
    plt.quiver(pbase[:-1], pvals[:-1], pbase_diff, pvals_diff, color=colors, scale_units='xy', angles='xy', scale=1)
    linebase = np.arange(Pmin-border, Pmax+border, (Pmax-Pmin)/20)
    plt.plot(linebase, [Sfun(x) for x in linebase], label='S')
    plt.plot(linebase, [Dfun(x) for x in linebase], label='D')
    plt.legend(loc='upper right',prop={'size':12})
    plt.xlabel('Prezzo')
    plt.ylabel('Domanda/Offerta')
    plt.grid(**GRID_OPTIONS)
    plt.savefig('./figs/%s.eps'%fname, dpi=SAVE_FIG_DPI)